apiVersion : apps/v1
kind: Deployment
metadata:
  name: "resource-3b09"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "resource-3b09"
  template:
    metadata:
      labels:
        app: "resource-3b09"
    spec:
      containers:
        - name: "resource-3b09"
          image: "nginx123.azurecr.io/resource"
          ports:
          - containerPort: 80